### PR TITLE
Spark 3.3.0 hadoop3

### PR DESCRIPTION
**Pull request by Michael-Gardner**
full spark 3.3.0 with hadoop 3 binaries

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@ghalliday can be merged. Update for submodules in the platform

**Comment by rpastrana** [comment]
@Michael-Gardner looks reasonable. Can you squash?
Also, how do we get a new branch dedicated to this?

**Comment by Michael-Gardner** [comment]
@rpastrana squashed.

**Comment by rpastrana** [comment]
Thanks.
@ghalliday please merge.

BTW, this merge has no affect on the submodule currently used in the HPCC-Platform repo:
https://github.com/hpcc-systems/HPCC-Platform/tree/master/plugins/spark

That said, 8.8.0 would have been a great target for this change, but their release schedule didn't give us enough time. Since this change includes Spark's formal log4j security patch, did not alter their APIs' signature, and has been tested successfully on our side, it could be integrated into the next point.

**Pull request merged**
